/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neuralnetwork;

//import java.awt.Color;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author Ben
 */
public class Window extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form Window
     */
    JFrame Parent;
    
   
    int Fitnesses = Testing.Scores.length;
    int[] Scores;
    public Window(JFrame Parent) {
        initComponents();
        this.Parent = Parent;
        Timer time = new Timer(0,this);
        time.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @Override
    public void paintComponent(Graphics g){
        //super.paintComponents(g);
        
        g.setColor(
            new Color(
                (float)javafx.scene.paint.Color.GOLD.getRed(),
                (float)javafx.scene.paint.Color.GOLD.getGreen(),
                (float)javafx.scene.paint.Color.GOLD.getBlue()
            )
        );
        g.setColor(Color.WHITE);
        //g.setColor((Color)javafx.scene.paint.Color.SLATEBLUE);
        //g.setColor(Color.RED);
        //this.jPanel1.paintAll(g);
        g.fillRect(0,0,Parent.getWidth(),Parent.getHeight());
        
        g.setColor(Color.BLUE);
        for (int i = 0; i < Fitnesses; i++) {
            
            int Width = Parent.getWidth()/Fitnesses;
            int Growth = map(Scores[i],0,Testing.creatures,0,Parent.getHeight()-100);
            
            g.fill3DRect(Width*i, (Parent.getHeight()-50)-Growth, Width, Growth, true);
            g.setColor(Color.black);
            g.setFont(g.getFont().deriveFont(Font.BOLD,20));
            
            g.drawString(i+": "+Scores[i],Width*i, (Parent.getHeight()-50)-Growth);
            g.setColor(Color.BLUE);
        }
        this.jLabel1.setText("Generation: "+Testing.gen);
        
    }
    int map(int x, int in_min, int in_max, int out_min, int out_max){
          return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
        }
    @Override
    public void actionPerformed(ActionEvent e) {
        int Creatures=0;
        for (int i = 0; i < Testing.Scores.length; i++) {
            Creatures+=Testing.Scores[i];
        }
        if(Creatures == Testing.creatures){
            Scores = Testing.Scores;
            repaint();
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new Color(0,0,0,0));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+10));
        jLabel1.setText("Generation: 0");
        jLabel1.setToolTipText("Algorithms Generation");

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+10));
        jLabel2.setText("Adverage: 0");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(421, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
